### PR TITLE
more benchmarks

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Super, thanks!

**Comment by cpitclaudel** [comment]
Btw, I've just pushed the FASTA example.

**Comment by DIJamner** [comment]
From a brief check, that function looks different from how I understood revcomp to work. Where does it reverse the string?

**Comment by cpitclaudel** [comment]
It doesn't, I've just applied the translation

**Comment by cpitclaudel** [comment]
(So you're right, I did complement, not reverse-complement)

**Pull request merged**
